# Generated by Django 4.0 on 2022-01-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alfabeto', models.CharField(max_length=9999)),
                ('Estados', models.CharField(max_length=9999)),
                ('EstadoInicial', models.CharField(max_length=9999)),
                ('EstadosDeAceitacao', models.CharField(max_length=9999)),
                ('DicionarioTransicao', models.CharField(max_length=9999)),
                ('Descricao', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaTuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alfabeto', models.CharField(max_length=9999)),
                ('Estados', models.CharField(max_length=9999)),
                ('EstadoInicial', models.CharField(max_length=9999)),
                ('EstadosDeAceitacao', models.CharField(max_length=9999)),
                ('DicionarioTransicao', models.CharField(max_length=9999)),
                ('Descricao', models.CharField(max_length=9999)),
            ],
        ),
    ]
